name = "rocky-mountain-aardvarks"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "aardvarks-db"
database_id = "00000000-0000-0000-0000-000000000000" # User will need to run wrangler d1 create
migrations_dir = "drizzle"
